#config_version=5

# To use this file with your own hardware, change the following lines:
# NET port: (line 19)
# EXP port: (line 23)
# Connect the Neuron via USB, plug in some LEDs
# Then run via `mpf -bt -c neuron`  The first LED of each port should light up in red, green, blue, white cycling on 1s intervals

hardware:
    platform: fast

mpf:
    report_crashes: never

fast:
  net:
    # debug: true      # uncomment to see full NET serial communication in the log. Search for `[NET]`
    controller: neuron
    port: /dev/tty.usbmodem14601     # Change me!

  exp:
    # debug: true      # uncomment to see full EXP serial communication in the log. Search for `[EXP]`
    port: /dev/tty.usbmodem14603     # Change me!
    boards:
      neuron:
        model: FP-EXP-2000

lights:
  led1-1:
    number: neuron-1-1  # Neuron LED Port 1, first LED in the chain
  led2-1:
    number: neuron-2-1  # Neuron LED Port 2, first LED in the chain
  led3-1:
    number: neuron-3-1  # Neuron LED Port 3, first LED in the chain
  led4-1:
    number: neuron-4-1  # Neuron LED Port 4, first LED in the chain

show_player:
  mode_attract_started: startup

shows:
  startup:
    - time: 0
      lights:
        led1-1:
          color: red
        led2-1:
          color: green
        led3-1:
          color: blue
        led4-1:
          color: white
    - time: '+1'
      lights:
        led1-1:
          color: green
        led2-1:
          color: blue
        led3-1:
          color: white
        led4-1:
          color: red
    - time: '+1'
      lights:
        led1-1:
          color: blue
        led2-1:
          color: white
        led3-1:
          color: red
        led4-1:
          color: green
    - time: '+1'
      lights:
        led1-1:
          color: white
        led2-1:
          color: red
        led3-1:
          color: green
        led4-1:
          color: blue
