#config_version=5

lights:
  led1:
    number: neuron-b0-p1-1
  led2:
    number: neuron-b0-p1-2
  led3:
    number: neuron-b0-p1-3
  led4:
    number: neuron-b0-p1-4
  led5:
    number: neuron-b0-p1-5
  led6:
    number: neuron-b0-p1-6
  led7:
    number: neuron-b0-p1-7
  led8:
    number: neuron-b0-p1-8
  led9:
    number: neuron-b0-p1-9
  led10:
    number: neuron-b0-p1-10
  led11:
    number: neuron-b0-p1-11
  led12:
    number: neuron-b0-p1-12
  led13:
    number: neuron-b0-p1-13
  led14:
    number: neuron-b0-p1-14
  led15:
    number: neuron-b0-p1-15
  led16:
    number: neuron-b0-p1-16
  led17:
    number: neuron-b0-p1-17
  led18:
    number: neuron-b0-p1-18
  led19:
    number: neuron-b0-p1-19
  led20:
    number: neuron-b0-p1-20
  led21:
    number: neuron-b0-p1-21
  led22:
    number: neuron-b0-p1-22
  led23:
    number: neuron-b0-p1-23
  led24:
    number: neuron-b0-p1-24
  led25:
    number: neuron-b0-p1-25
  led26:
    number: neuron-b0-p1-26
  led27:
    number: neuron-b0-p1-27
  led28:
    number: neuron-b0-p1-28
  led29:
    number: neuron-b0-p1-29
  led30:
    number: neuron-b0-p1-30
  led31:
    number: neuron-b0-p1-31
  led32:
    number: neuron-b0-p1-32
  led33:
    number: neuron-b0-p2-1
  led34:
    number: neuron-b0-p2-2
  led35:
    number: neuron-b0-p2-3
  led36:
    number: neuron-b0-p2-4
  led37:
    number: neuron-b0-p2-5
  led38:
    number: neuron-b0-p2-6
  led39:
    number: neuron-b0-p2-7
  led40:
    number: neuron-b0-p2-8
  led41:
    number: neuron-b0-p2-9
  led42:
    number: neuron-b0-p2-10
  led43:
    number: neuron-b0-p2-11
  led44:
    number: neuron-b0-p2-12
  led45:
    number: neuron-b0-p2-13
  led46:
    number: neuron-b0-p2-14
  led47:
    number: neuron-b0-p2-15
  led48:
    number: neuron-b0-p2-16
  led49:
    number: neuron-b0-p2-17
  led50:
    number: neuron-b0-p2-18
  led51:
    number: neuron-b0-p2-19
  led52:
    number: neuron-b0-p2-20
  led53:
    number: neuron-b0-p2-21
  led54:
    number: neuron-b0-p2-22
  led55:
    number: neuron-b0-p2-23
  led56:
    number: neuron-b0-p2-24
  led57:
    number: neuron-b0-p2-25
  led58:
    number: neuron-b0-p2-26
  led59:
    number: neuron-b0-p2-27
  led60:
    number: neuron-b0-p2-28
  led61:
    number: neuron-b0-p2-29
  led62:
    number: neuron-b0-p2-30
  led63:
    number: neuron-b0-p2-31
  led64:
    number: neuron-b0-p2-32
  led65:
    number: neuron-b0-p3-1
  led66:
    number: neuron-b0-p3-2
  led67:
    number: neuron-b0-p3-3
  led68:
    number: neuron-b0-p3-4
  led69:
    number: neuron-b0-p3-5
  led70:
    number: neuron-b0-p3-6
  led71:
    number: neuron-b0-p3-7
  led72:
    number: neuron-b0-p3-8
  led73:
    number: neuron-b0-p3-9
  led74:
    number: neuron-b0-p3-10
  led75:
    number: neuron-b0-p3-11
  led76:
    number: neuron-b0-p3-12
  led77:
    number: neuron-b0-p3-13
  led78:
    number: neuron-b0-p3-14
  led79:
    number: neuron-b0-p3-15
  led80:
    number: neuron-b0-p3-16
  led81:
    number: neuron-b0-p3-17
  led82:
    number: neuron-b0-p3-18
  led83:
    number: neuron-b0-p3-19
  led84:
    number: neuron-b0-p3-20
  led85:
    number: neuron-b0-p3-21
  led86:
    number: neuron-b0-p3-22
  led87:
    number: neuron-b0-p3-23
  led88:
    number: neuron-b0-p3-24
  led89:
    number: neuron-b0-p3-25
  led90:
    number: neuron-b0-p3-26
  led91:
    number: neuron-b0-p3-27
  led92:
    number: neuron-b0-p3-28
  led93:
    number: neuron-b0-p3-29
  led94:
    number: neuron-b0-p3-30
  led95:
    number: neuron-b0-p3-31
  led96:
    number: neuron-b0-p3-32
  led97:
    number: neuron-b0-p4-1
  led98:
    number: neuron-b0-p4-2
  led99:
    number: neuron-b0-p4-3
  led100:
    number: neuron-b0-p4-4
  led101:
    number: neuron-b0-p4-5
  led102:
    number: neuron-b0-p4-6
  led103:
    number: neuron-b0-p4-7
  led104:
    number: neuron-b0-p4-8
  led105:
    number: neuron-b0-p4-9
  led106:
    number: neuron-b0-p4-10
  led107:
    number: neuron-b0-p4-11
  led108:
    number: neuron-b0-p4-12
  led109:
    number: neuron-b0-p4-13
  led110:
    number: neuron-b0-p4-14
  led111:
    number: neuron-b0-p4-15
  led112:
    number: neuron-b0-p4-16
  led113:
    number: neuron-b0-p4-17
  led114:
    number: neuron-b0-p4-18
  led115:
    number: neuron-b0-p4-19
  led116:
    number: neuron-b0-p4-20
  led117:
    number: neuron-b0-p4-21
  led118:
    number: neuron-b0-p4-22
  led119:
    number: neuron-b0-p4-23
  led120:
    number: neuron-b0-p4-24
  led121:
    number: neuron-b0-p4-25
  led122:
    number: neuron-b0-p4-26
  led123:
    number: neuron-b0-p4-27
  led124:
    number: neuron-b0-p4-28
  led125:
    number: neuron-b0-p4-29
  led126:
    number: neuron-b0-p4-30
  led127:
    number: neuron-b0-p4-31
  led128:
    number: neuron-b0-p4-32